version: '3.8'

services:
  backend:
    image: dalzihn/hpc_group02_backend
    ports:
      - "8000:8000"
      - "8001:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
    depends_on:
      - redis

  frontend:
    image: dalzihn/hpc_group02_frontend
    ports:
      - "3000:80"
      - "3001:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
    depends_on:
      - backend

  redis:
    image: redis:7.0.10
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback

  