version: '3.8'
services:
  backend:
    image: dalzihn/hpc_nhom2_backend
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      placement:
        constraints: 
          - node.hostname == docker-desktop
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    environment:
      - API_URL=http://localhost:8000
      - DEPLOY_URL=http://localhost:3000
      - FRONTEND_PORT=3000
      - BACKEND_PORT=8000
      - BACKEND_HOST=0.0.0.0
    depends_on:
      - redis

  frontend:
    image: dalzihn/hpc_nhom2_frontend
    ports:
      - "3000:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    environment:
      - API_URL=http://localhost:8000
      - LISTEN_PORT=80
      - SERVER_NAME=frontend
      - PROXY_BACKEND=/_event
    depends_on:
      - backend

  redis:
    image: redis:7.0.10
    deploy:
      replicas: 2
      placement:
        constraints: 
          - node.hostname == docker-desktop
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback


  